services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  main:
    build:
      context: ./teperunner-main
      dockerfile: Dockerfile
    container_name: teperunner-main
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - "3000:3000"

  worker:
    build:
      context: ./teperunner-worker
      dockerfile: Dockerfile
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure