# Generated by Django 5.1.3 on 2024-11-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='ip',
            field=models.CharField(max_length=200),
        ),
    ]
